# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: my-personal-computer

jobs:
- job: Build
  steps:
  - task: Maven@2
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: Test
  dependsOn: Build
  steps:
  - script: echo "Este es un paso vacío que no hace nada."
    displayName: 'Paso vacío'
  # Agregar las tareas necesarias para ejecutar las pruebas después de la construcción

- job: Deploy
  dependsOn: Test
  steps:
  - script: echo "Este es un paso vacío que no hace nada."
    displayName: 'Paso vacío'
  # Agregar las tareas necesarias para desplegar después de las pruebas